"""Add column to recipes image url

Revision ID: 19b8773aeba6
Revises: 1a3516d0e6f5
Create Date: 2021-10-17 08:55:48.098229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b8773aeba6'
down_revision = '1a3516d0e6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_url')
    # ### end Alembic commands ###
