"""Change column name

Revision ID: 2ed45bbe54fa
Revises: 19b8773aeba6
Create Date: 2021-10-18 21:13:43.351482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed45bbe54fa'
down_revision = '19b8773aeba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('user_being_followed_id', sa.Integer(), nullable=False))
    op.drop_constraint('follows_user_follower_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['user_being_followed_id'], ['id'], ondelete='cascade')
    op.drop_column('follows', 'user_follower_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('user_follower_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_user_follower_id_fkey', 'follows', 'users', ['user_follower_id'], ['id'], ondelete='CASCADE')
    op.drop_column('follows', 'user_being_followed_id')
    # ### end Alembic commands ###
