"""update column

Revision ID: 67f8af377d60
Revises: 890907603cd1
Create Date: 2021-10-19 17:51:25.840409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67f8af377d60'
down_revision = '890907603cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredients', sa.Text(), nullable=False))
    op.drop_column('recipes', 'ingredient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('ingredient', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('recipes', 'ingredients')
    # ### end Alembic commands ###
