"""Add column

Revision ID: 890907603cd1
Revises: 2ed45bbe54fa
Create Date: 2021-10-19 14:20:36.049095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890907603cd1'
down_revision = '2ed45bbe54fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('approx_calories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'approx_calories')
    # ### end Alembic commands ###
