"""add column reset password to user

Revision ID: 94bd0b2e304c
Revises: 877c28f2f2ed
Create Date: 2022-04-08 15:58:10.662410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bd0b2e304c'
down_revision = '877c28f2f2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_reset_password', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_reset_password')
    # ### end Alembic commands ###
