"""Create User and Follows table.

Revision ID: 94d1b6aa93ad
Revises: 
Create Date: 2021-10-14 23:17:56.214729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d1b6aa93ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('auth_reset_password', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('user_follower_id', sa.Integer(), nullable=False),
    sa.Column('user_following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_follower_id'], ['users.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_following_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_follower_id', 'user_following_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
