"""add column to category

Revision ID: 9730beb34f26
Revises: 77acd805b9cf
Create Date: 2021-11-05 14:27:07.893858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9730beb34f26'
down_revision = '77acd805b9cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('banner_img_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'banner_img_url')
    # ### end Alembic commands ###
