"""update

Revision ID: ce5ecd91638c
Revises: 9730beb34f26
Create Date: 2021-11-05 23:55:35.193047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce5ecd91638c'
down_revision = '9730beb34f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    op.drop_column('recipes', 'total_rate')
    op.drop_column('recipes', 'average_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('average_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('recipes', sa.Column('total_rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('rates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='rates_recipe_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rates_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='rates_pkey')
    )
    # ### end Alembic commands ###
