"""add new colums to recipe table.

Revision ID: de3b7fd7dd07
Revises: 67f8af377d60
Create Date: 2021-11-03 14:29:49.700516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3b7fd7dd07'
down_revision = '67f8af377d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('serving', sa.Integer(), nullable=False))
    op.add_column('recipes', sa.Column('prep', sa.String(length=30), nullable=False))
    op.add_column('recipes', sa.Column('cook', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'cook')
    op.drop_column('recipes', 'prep')
    op.drop_column('recipes', 'serving')
    # ### end Alembic commands ###
